final_project_DSC/controllers/AdrtController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Adrt;
use app\models\AdrtSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\systemxadmin\models\User;
use app\modules\systemxadmin\models\AuthAssignment;
use app\modules\systemxadmin\models\AuthItem;
use app\modules\systemxadmin\models\UserSearch;
use yii\web\UploadedFile;
/**
 * AdrtController implements the CRUD actions for Adrt model.
 */
class AdrtController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Adrt models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdrtSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Adrt model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView()
    {
        $model = Adrt::find()->orderBy(['id_adrt'=>'DESC'])->one();

        $model_user = User::find()->where(['id'=>$model->updated_by])->one();

        $user = Yii::$app->user->identity;
        $role = AuthAssignment::find()->where(['user_id'=>$user->id])->one();

        return $this->render('view', [
            'model' => $model,
            'model_user' => $model_user,
            'role' => $role,
        ]);
    }

    /**
     * Creates a new Adrt model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Adrt();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_adrt]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Adrt model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
             
            $file = UploadedFile::getInstance($model, 'file');
            if (!is_null($file)) {
                $tmp = explode('.', $file->name);
                $ext_foto = end($tmp);
                $model->file_adrt = Yii::$app->security->generateRandomString().".{$ext_foto}";
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/upload/adrt/';
                $path_file = Yii::$app->params['uploadPath'] . $model->file_adrt;
                
                $file->saveAs($path_file);  
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'ADRT Berhasil Diupdate');
            } else {
                Yii::$app->session->setFlash('error', 'ADRT Gagal Diupdate');
            }

            return $this->redirect(['view']);
        } else {
            
            return $this->render('update', [
                'model' => $model,
                
            ]);
        }
    }

    /**
     * Deletes an existing Adrt model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Adrt model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Adrt the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Adrt::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

final_project_DSC/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\RegistrationForm;
//use app\models\User;
//use hscstudio\mimin\models\AuthAssignment;
use app\models\TUser;
use app\modules\systemxadmin\models\User;
use app\modules\systemxadmin\models\AuthAssignment;
use app\modules\systemxadmin\models\AuthItem;
use app\modules\systemxadmin\models\UserSearch;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        
        if (!Yii::$app->user->isGuest) {
            //return $this->goHome();
            return $this->redirect(['site/index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
            //return $this->redirect(['site/index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);



    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /*
        Fungsi Register : Untuk menambahkan user baru
    */
    public function actionRegister()
    {
        
        $model = new User();
        $modelRole = new AuthAssignment();

        if ($model->load(Yii::$app->request->post())) {
            $password = $model->password_hash;
            //print_r($password);die;
            $model->setPassword($password);
            $model->status = 10;
            if ($model->save()) {
                $user = TUser::find()->where(['username' => $model->username])->andWhere(['email'=>$model->email])->one();
                $modelRole->item_name = "PESERTA";
                $modelRole->user_id = $user->id;

                if($modelRole->save()){
                    $email = \Yii::$app->mailer->compose()
                    ->setFrom(['henny.panjaitan3004@gmail.com'=>'Del Data Science Club'])
                    ->setTo($user->email)
                    ->setSubject('Informasi Pemberitahuan Verifikasi Jadi Anggota')
                    ->setHtmlBody('
                        <b>Terima Kasih Telah Melakukan Registrasi Pada Del Data Science Club</b>
                        <br><br>
                        <b>Akun anda telah diverifikasi, Silahkan LOGIN menggunakan username dan password yang anda daftarkan</b>')
                    ->send();

                    if($email){
                        Yii::$app->session->setFlash('success', "Registrasi User Berhasil");
                    }
                    
                }else{
                    $user->delete();
                    Yii::$app->session->setFlash('danger', 'Mohon Maaf, Registrasi User Gagal');
                }

                
            } else {
                Yii::$app->session->setFlash('danger', 'Mohon Maaf, Registrasi User Gagal');
            }

            return $this->redirect(['login']);
        } else {
            return $this->render('register_user', [
                'model' => $model,
            ]);
        }
        
    }

    public function actionViewProfile($id)
    {
        $model = User::findOne($id);
        
        return $this->render('view_profile', [
            'model' => $model,
            'id' => $id,
        ]);
    }


    public function actionUpdateuser($id)
    {
        $model = User::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
             
            $foto_profil = UploadedFile::getInstance($model, 'foto_profil');
            if (!is_null($foto_profil)) {
                $tmp = explode('.', $foto_profil->name);
                $ext_foto = end($tmp);
                //$ext_foto = end((explode(".", $image_foto->name)));
                  // generate a unique file name to prevent duplicate filenames
                $model->foto = Yii::$app->security->generateRandomString().".{$ext_foto}";
                
                // the path to save file, you can set an uploadPath
                // in Yii::$app->params (as used in example below)
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/foto_profil/';
                $path_foto = Yii::$app->params['uploadPath'] . $model->foto;
                
                $foto_profil->saveAs($path_foto);  
                    
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'User berhasil diupdate');
            } else {
                Yii::$app->session->setFlash('error', 'User gagal diupdate');
            }
            return $this->redirect(['view-profile','id'=>$id]);
        } else {
            
            return $this->renderAjax('_form_profil', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdatepassword($id)
    {
        $model = User::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!empty($model->new_password)) {
                $model->setPassword($model->new_password);
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Password berhasil diupdate');
            } else {
                Yii::$app->session->setFlash('error', 'Password gagal diupdate');
            }
            return $this->redirect(['view-profile','id'=>$id]);
        } else {
            
            return $this->renderAjax('_form_update_password', [
                'model' => $model,
            ]);
        }
    }

}

final_project_DSC/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo "";//echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2020 <a href="#">Del Data Science Club System</a>.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

final_project_DSC/views/layouts/left.php
<?php
    //use hscstudio\mimin\components\Mimin;
    use app\modules\systemxadmin\components\Mimin;
?>

<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                
                <?php 
                    if(!Yii::$app->user->isGuest){
                        if(Yii::$app->user->identity->foto!=null){
                            $urlImage = Yii::getAlias('@web').'/foto_profil/'.Yii::$app->user->identity->foto;

                ?>
                            <img src="<?= $urlImage;?>" class="img-circle" alt="User Image" style="height: 50px;width: 50px;"/>
                <?php
                        }else{
                            $urlImage = Yii::getAlias('@web').'/images/profil.png';
                ?>
                            <img src="<?= $urlImage;?>" class="img-circle" alt="User Image" style="height: 40px;width: 40px;"/>
                <?php            
                        }
                        
                    }
                ?>
            </div>
            <div class="pull-left info">
                <p>
                    <?php 
                        if(!Yii::$app->user->isGuest){
                            echo Yii::$app->user->identity->username;
                        }else{
                            echo "Guest";
                        }
                    ?>

                    


                </p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <?php
            $user = Yii::$app->user->identity;
            $menuItems[] = ['label' => 'MENU', 'options' => ['class' => 'header']];

            if (\Yii::$app->user->isGuest){
                $menuItems[] = ['label' => 'LOGIN', 'url' => ['/site/login']];
                
            }
            else{
                
                $menuItems[] = ['label' => 'HOME', 'icon' => 'home', 'url' => ['site/index']];
                
                $menuItems[] = ['label' => 'MATERI', 'icon' => 'file-text-o', 'url' => ['kategori/home-kategori-materi']];

                $menuItems[] = ['label' => 'TANTANGAN', 'icon' => 'database', 'url' => ['tantangan/index']];

                $menuItems[] = ['label' => 'ADRT', 'icon' => 'exchange', 'url' => ['adrt/view']];
                
                $menuItems[] = ['label' => 'DAFTAR USER', 'icon' => 'users', 'url' => ['pengurus/home-daftar-user']];

                $menuItems[] = ['label' => 'PROGRAM KERJA', 'icon' => 'dashboard', 'url' => ['program-kerja/index']];

                $menuItems[] = ['label' => 'VERIFIKASI ANGGOTA', 'icon' => 'address-card', 'url' => ['pengurus/list-verifikasi-pendaftar']];

                $menuItems[] = [
                        'label' => 'MANAJEMEN DATA',
                        'icon' => 'bars',
                        'url' => '#',
                        'items' => [
                            ['label' => 'DATA KATEGORI', 'icon' => 'database', 'url' => ['kategori/index'],],    
                        ],
                    ];    

                $menuItems[] = 
                    ['label' => 'ACCESS CONTROL','icon'=>'th-large' ,'items' => [
                        ['label' => 'ROUTE', 'icon' => 'asterisk', 'url' => ['/systemxadmin/route/index'],],
                        ['label' => 'ROLE', 'icon' => 'bars', 'url' => ['/systemxadmin/role/index'],],
                        ['label' => 'USER', 'icon' => 'drivers-license-o', 'url' => ['/systemxadmin/user/index'],],
                        
                    ],
                ];
                
                
            }

            $menuItems = Mimin::filterMenu($menuItems);

            echo dmstr\widgets\Menu::widget(
                    [
                        'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                        'items' => $menuItems,
                    ]
            )
        ?>

      

    </section>

</aside>

final_project_DSC/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

final_project_DSC/views/layouts/main_old.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use hscstudio\mimin\components\Mimin;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
            $user = Yii::$app->user->identity;
            //$menuItems[] = ['label' => 'MENU', 'options' => ['class' => 'header']];

            if (\Yii::$app->user->isGuest){
               
                $menuItems[] = ['label' => 'HOME', 'url' => ['/site/index']]; 
                $menuItems[] = ['label' => 'LOGIN', 'url' => ['/site/login']];
                $menuItems[] = ['label' => 'DAFTAR', 'url' => ['/site/register']];

                
            }
            else{
                
                $menuItems[] = ['label' => 'HOME', 'icon' => 'home', 'url' => ['site/index']];

                $menuItems[] = ['label' => 'VOTING', 'icon' => 'home', 'url' => ['hasil-voting/online-voting']];
                
                
                $menuItems[] = 
                    ['label' => 'DATA VOTING','icon'=>'th-large' ,'items' => [
                        ['label' => 'MASTER DATA VOTING', 'icon' => 'asterisk', 'url' => ['/voting/index'],],
                        ['label' => 'HASIL VOTING', 'icon' => 'bars', 'url' => ['/voting/index-hasil-voting'],],
                        ['label' => 'REKAPITULASI VOTING USER', 'icon' => 'bars', 'url' => ['/voting/index-pengguna-voting'],],
                    ],
                ];

                $menuItems[] = 
                    ['label' => 'ACCESS CONTROL','icon'=>'th-large' ,'items' => [
                        ['label' => 'ROLE', 'icon' => 'bars', 'url' => ['/mimin/role/index'],],
                        ['label' => 'USER', 'icon' => 'drivers-license-o', 'url' => ['/mimin/user/index'],],
                        ['label' => 'ROUTE', 'icon' => 'asterisk', 'url' => ['/mimin/route/index'],],
                        
                    ],
                ];

                $menuItems[] = ['label' => 'Logout ('.Yii::$app->user->identity->username.')', 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post'],];
            
                
                    
            }

            $menuItems = Mimin::filterMenu($menuItems);

        ?>
    <?php
    NavBar::begin([
        'brandLabel' => '<b><i class="text-primary">Online Voting System</i></b>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Developer Team of D3TI (Nama_Kelompok) <?= date('Y') ?></p>

        <p class="pull-right">Web Programming Project</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>