final_project_DSC/models/Materi.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
/**
 * This is the model class for table "materi".
 *
 * @property int $id_materi
 * @property string $judul_materi
 * @property string|null $deskripsi_materi
 * @property string $file_materi
 * @property int $id_kategori
 * @property string|null $created_at
 * @property int|null $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 *
 * @property Kategori $kategori
 */
class Materi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $file;

    public static function tableName()
    {
        return 'materi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['judul_materi', 'file_materi', 'id_kategori','id_setting'], 'required'],
            [['id_kategori', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['judul_materi', 'file_materi'], 'string', 'max' => 255],
            [['deskripsi_materi'], 'string'],
            [['id_kategori'], 'exist', 'skipOnError' => true, 'targetClass' => Kategori::className(), 'targetAttribute' => ['id_kategori' => 'id_kategori']],

            [['file'], 'safe'],
            [['file'], 'file', 'extensions'=>'jpg, jpeg, png, tif, pdf, docx, doc, zip, rar'],
            [['file'], 'file', 'maxSize' => 1024 * 1024 * 1024],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_materi' => 'ID Materi',
            'judul_materi' => 'Judul Materi',
            'deskripsi_materi' => 'Deskripsi Materi',
            'file_materi' => 'File Materi',
            'id_kategori' => 'ID Kategori',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'id_setting' => 'ID Setting',
        ];
    }

    public function behaviors()
    {
       return [
           'timestamp' => [
               'class' => TimestampBehavior::className(),
               'attributes' => [
                   ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                   ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
               ],
               'value' => new Expression('NOW()'),
           ],

       ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }
        if(ActiveRecord::EVENT_BEFORE_INSERT){
            $this->created_by = Yii::$app->user->identity->id;
            $this->updated_by = Yii::$app->user->identity->id;
        }else if(ActiveRecord::EVENT_BEFORE_UPDATE){
            $this->updated_by = Yii::$app->user->identity->id;
        }

        return true;
    }

    /**
     * Gets query for [[Kategori]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKategori()
    {
        return $this->hasOne(Kategori::className(), ['id_kategori' => 'id_kategori']);
    }

    public function getSetting()
    {
        return $this->hasOne(Setting::className(), ['id_setting' => 'id_setting']);
    }
}

final_project_DSC/controllers/MateriController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Materi;
use app\models\MateriSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Setting;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use app\models\Kategori;
use app\modules\systemxadmin\models\User;
use app\modules\systemxadmin\models\AuthAssignment;
use app\modules\systemxadmin\models\AuthItem;
use app\modules\systemxadmin\models\UserSearch;

/**
 * MateriController implements the CRUD actions for Materi model.
 */
class MateriController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Materi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MateriSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Materi model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $model_user = User::find()->where(['id'=>$model->updated_by])->one();

        $user = Yii::$app->user->identity;
        $role = AuthAssignment::find()->where(['user_id'=>$user->id])->one();

        return $this->render('view', [
            'model' => $model,
            'model_user' => $model_user,
            'role' => $role,
        ]);
    }

    /**
     * Creates a new Materi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_kategori)
    {
        $model = new Materi();
        $setting = Setting::find()->where(['active'=>10])->orderBy(['id_setting' => 'DESC'])->one();
        $kategori = Kategori::find()->where(['id_kategori' =>$id_kategori])->one();

        if ($model->load(Yii::$app->request->post())) {
             
            $file = UploadedFile::getInstance($model, 'file');
            if (!is_null($file)) {
                $tmp = explode('.', $file->name);
                $ext_foto = end($tmp);
                //$ext_foto = end((explode(".", $image_foto->name)));
                  // generate a unique file name to prevent duplicate filenames
                $model->file_materi = Yii::$app->security->generateRandomString().".{$ext_foto}";
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/upload/materi/';
                $path_file = Yii::$app->params['uploadPath'] . $model->file_materi;
                
                $file->saveAs($path_file);  
            }
            $model->id_setting = $setting->id_setting;
            $model->id_kategori = $id_kategori;
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Materi Berhasil Diupload');
            } else {
                Yii::$app->session->setFlash('error', 'Materi Gagal Diupload');
            }

            return $this->redirect(['view-materi','id_kategori' =>$id_kategori]);
        } else {
            
            return $this->render('create', [
                'model' => $model,
                'kategori' =>$kategori,
            ]);
        }
    }

    /**
     * Updates an existing Materi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        //$model = new Materi();
        $setting = Setting::find()->where(['active'=>10])->orderBy(['id_setting' => 'DESC'])->one();
        $kategori = Kategori::find()->where(['id_kategori' =>$model->id_kategori])->one();

        if ($model->load(Yii::$app->request->post())) {
             
            $file = UploadedFile::getInstance($model, 'file');
            if (!is_null($file)) {
                $tmp = explode('.', $file->name);
                $ext_foto = end($tmp);
                //$ext_foto = end((explode(".", $image_foto->name)));
                  // generate a unique file name to prevent duplicate filenames
                $model->file_materi = Yii::$app->security->generateRandomString().".{$ext_foto}";
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/upload/materi/';
                $path_file = Yii::$app->params['uploadPath'] . $model->file_materi;
                
                $file->saveAs($path_file);  
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Materi Berhasil Diupdate');
            } else {
                Yii::$app->session->setFlash('error', 'Materi Gagal Diupdate');
            }

            return $this->redirect(['view-materi','id_kategori' =>$model->id_kategori]);
        } else {
            
            return $this->render('update', [
                'model' => $model,
                'kategori' =>$kategori,
            ]);
        }
    }

    /**
     * Deletes an existing Materi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Materi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Materi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Materi::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /*
        Fungsi Untuk View Semua Materi Yang Diupload Per Kategori
    */
    public function actionViewMateri($id_kategori)
    {

        $setting = Setting::find()->where(['active'=>10])->orderBy(['id_setting' => 'DESC'])->one();

        $arrayTahun = ArrayHelper::map(Setting::find()->orderBy(['id_setting' => 'DESC'])->all(),'id_setting','tahun_aktif');

        $materi = Materi::find()->where(['id_setting' => $setting->id_setting])->andWhere(['id_kategori' => $id_kategori])->all();

        $kategori = Kategori::find()->where(['id_kategori' =>$id_kategori])->one();

        $pembina = User::find()->join('JOIN','auth_assignment','auth_assignment.user_id = t_user.id')->where(['auth_assignment.item_name'=>'PEMBINA'])->all();
        $countAnggota =  User::find()->join('JOIN','auth_assignment','auth_assignment.user_id = t_user.id')->where(['auth_assignment.item_name'=>'ANGGOTA'])->count();

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchAnggota(Yii::$app->request->queryParams);

        $user = Yii::$app->user->identity;
        $role = AuthAssignment::find()->where(['user_id'=>$user->id])->one();


        return $this->render('view_materi', [
            'setting' => $setting,
            'materi' => $materi,
            'arrayTahun' => $arrayTahun,
            'kategori' =>$kategori,
            'pembina' => $pembina,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'countAnggota' => $countAnggota,
            'role' => $role,

        ]);
    }

}

final_project_DSC/views/materi/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use dosamigos\ckeditor\CKEditor;
use skeeks\yii2\ckeditor\CKEditorWidget;
use skeeks\yii2\ckeditor\CKEditorPresets;

/* @var $this yii\web\View */
/* @var $model app\models\Materi */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="materi-form">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <center><h3>FORM UPLOAD MATERI <span class="text-success"><?= $kategori->nama_kategori;?></span></h3></center>
                    <p align="right">
                        <?= Html::a('<span class="glyphicon glyphicon-step-backward"></span>Kembali', ['materi/view-materi','id_kategori'=> $kategori->id_kategori], ['class' => 'btn btn-default']) ?>
                    </p>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php $form = ActiveForm::begin([
                        /*'action' => ['materi/create','id_kategori'=>$kategori->id_kategori],
                        'method' => 'post',*/
                    ]); ?>

                    <?= $form->field($model, 'judul_materi')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'deskripsi_materi')->widget(CKEditorWidget::className(), [
                        'options' => ['rows' => 4],
                        'preset' => CKEditorPresets::FULL
                    ]) ?>

                    <?= $form->field($model, 'file')->widget(FileInput::classname(), 
                        [
                            'pluginOptions'=>[
                                'allowedFileExtensions'=>['jpg','jpeg','png','pdf','docx','doc','zip','rar'],
                                'dropZoneEnabled'=> false,
                                'browseLabel' =>  'Upload File Materi'
                            ],
                        ]) 
                    ?>

    

                    

                    <div class="form-group">
                        <center><?= Html::submitButton('SIMPAN MATERI', ['class' => 'btn btn-success']) ?></center>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
    

</div>

final_project_DSC/views/materi/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MateriSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="materi-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_materi') ?>

    <?= $form->field($model, 'judul_materi') ?>

    <?= $form->field($model, 'deskripsi_materi') ?>

    <?= $form->field($model, 'file_materi') ?>

    <?= $form->field($model, 'id_kategori') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

final_project_DSC/views/materi/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Materi */

$this->title = 'Upload Materi';

?>
<div class="materi-create">

    <?= $this->render('_form', [
        'model' => $model,
        'kategori' =>$kategori,
    ]) ?>

</div>

final_project_DSC/views/materi/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\MateriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Materis';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="materi-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Materi', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_materi',
            'judul_materi',
            'deskripsi_materi',
            'file_materi',
            'id_kategori',
            //'created_at',
            //'created_by',
            //'updated_at',
            //'updated_by',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

final_project_DSC/views/materi/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Materi */

$this->title = 'Update Materi';

?>
<div class="materi-update">

    <?= $this->render('_form', [
        'model' => $model,
        'kategori' =>$kategori,
    ]) ?>

</div>

final_project_DSC/views/materi/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model app\models\Materi */

$this->title = 'View Materi';
/*$this->params['breadcrumbs'][] = ['label' => 'Materis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;*/
\yii\web\YiiAsset::register($this);
?>
<div class="materi-view">

    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="box box-widget">
            <div class="box-header with-border">
                <table class="table">
                    <tr>
                        <td colspan="2" align="center"><h4> <b class="text-success"><?= $model->judul_materi;?></b></h4></td>
                        <td align="right">
                            <?= Html::a('<span class="glyphicon glyphicon-step-backward"></span>Kembali', ['materi/view-materi','id_kategori'=> $model->id_kategori], ['class' => 'btn btn-default']) ?>
                            <?php
                                if($role->item_name == 'PEMBINA' || $role->item_name == 'ADMINISTRATOR' || $role->item_name == 'PENGURUS'){
                                    echo Html::a('<span class="glyphicon glyphicon-pencil"></span> UPDATE MATERI', ['update', 'id' => $model->id_materi], ['class' => 'btn btn-success']);
                                    echo Html::a('<span class="glyphicon glyphicon-trash"></span> HAPUS', ['delete', 'id' => $model->id_materi], ['class' => 'btn btn-danger','data' => [
                                            'confirm' => 'Apakah anda yakin menghapus data ini?',
                                            'method' => 'post',
                                        ],
                                    ]);
                                } 
                                 
                            ?>
                            
                        </td>
                    </tr>
                </table>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table">
                    <tr>
                        <th>Deskripsi Materi</th>
                    </tr>
                    <tr>
                        <td>
                            <?= $model->deskripsi_materi; ?>
                        </td>
                    </tr>
                     <tr>
                        <th>Download File Materi :  
                        <?php
                            $url = Url::base().'/upload/materi/'.$model->file_materi;
                            echo Html::a(''.$model->judul_materi, $url, ['class' => '','target' => '_blank']); 
                        ?>
                        </th>
                    </tr>
                    
                </table>
                
            </div>
            <div class="box-footer with-border">
                <p align="right">
                    <i>Last Update</i> : <?=$model->updated_at;?>
                    <br>
                    <i>Update By</i> : <?=$model_user->nama_user;?>
                </p>
            </div>
        </div>
    </div>
</div>

final_project_DSC/views/materi/view_materi.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KategoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Upload Materi';

//$this->params['breadcrumbs'][] = $this->title;
?>

<?php
        
    Modal::begin([
        'header' => '<center><h4>DATA</h4></center>',
        'id' => 'modal-data',
        'size' => 'modal-md',
        'options' => [
              'tabindex' => false, 
          ],
    ]);

    echo '<div id="content-modal-data"></div>';
    Modal::end();
?>

<div class="kategori-index">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="box box-success">
                <div class="box-header with-border">
                    <table class="table">
                        <tr>
                            <td colspan="2" align="center"><h4>MATERI <b class="text-success"><?= $kategori->nama_kategori;?></b> TAHUN <?= $setting->tahun_aktif;?></h4></td>
                            
                            <td align="right">
                                <?php
                                    if($role->item_name == 'PEMBINA' || $role->item_name == 'ADMINISTRATOR' || $role->item_name == 'PENGURUS'){
                                        echo Html::a('<span class="glyphicon glyphicon-cloud-upload"></span> UPLOAD MATERI', ['materi/create','id_kategori'=>$_GET['id_kategori']], ['class' => 'btn btn-success']);
                                    } 
                                     
                                ?>
                            </td>
                        </tr>
                        <tr></tr>
                    </table>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php
                        if(is_null($materi)){
                            echo "Materi Saat Ini Belum Ada";
                        }else{
                            $i = 1;
                            foreach ($materi as $key => $value) {
                                                           
                    ?>
                            <ul class="products-list product-list-in-box">
                                <li class="item">
                                  <div class="product-img">
                                    <i class="fa fa-book fa-3x"></i>
                                  </div>
                                  <div class="product-info">
                                    <?= Html::a('<h4>'.$value['judul_materi'].'</h4>', ['materi/view','id'=>$value['id_materi']], ['class' => '']) ?>

                                    <a href="javascript:void(0)" class="product-title">
                                      <span class="label label-info pull-right"><?= "Materi ".$i;?></span></a>
                                    <span class="product-description">
                                        <?php
                                            $url = Url::base().'/upload/materi/'.$value['file_materi'];
                                            echo Html::a('<i class="fa fa-download"></i> Download File Materi', $url, ['class' => 'btn btn-default btn-sm','target' => '_blank']) 
                                        ?>
                                    </span>
                                  </div>
                                </li>
                               
                            </ul>
                    <?php
                                $i++;
                            }        
                        }
                    ?>

                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="box box-solid box-success">
                <div class="box-header with-border">
                    <center>
                      FILTER DAN KETERANGAN MATERI
                    </center>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table">
                        <tr>
                            <th>Filter Materi</th>
                        </tr>
                        <tr>
                            <td>
                                <?php
                                    echo Select2::widget([
                                        'name' => 'id_tahun',
                                        'data' => $arrayTahun,
                                        'options' => [
                                            'placeholder' => 'Filter Data Berdasarkan Tahun ...',
                                            'id'=>'id_tahun'
                                        ],
                                        'pluginOptions' => [
                                            'allowClear' => true
                                        ],
                                    ]);
                                ?>
                            </td>
                        </tr>

                        <tr>
                            <th>Keterangan Materi</th>
                        </tr>
                        <tr align="center">
                            <td><b class="text-success"><?= $kategori->nama_kategori;?> - TAHUN <?= $setting->tahun_aktif;?></b></td>
                        </tr>

                        <tr>
                            <th>Pembina</th>
                        </tr>
                    <?php
                        foreach ($pembina as $key => $value) {
                    ?>
                        <tr align="center">
                            <td><h3 class="label label-primary"><?= $value['nama_user'];?></h3></td>
                        </tr>
                    <?php        
                        }
                    ?>
                        
                    </table>
                    
                </div>
            </div>

            <div class="box box-solid box-danger">
                <div class="box-header with-border">
                    <center>
                      DAFTAR ANGGOTA
                    </center>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table">
                        <tr>
                            <th>Jumlah Anggota : <?= Html::a($countAnggota.' orang', ['pengurus/list-user','role'=>'ANGGOTA'], ['class' => 'text-danger','title' => 'LIHAT DAFTAR ANGGOTA KESELURUHAN','data-toggle' => 'tooltip',]) ?></th>
                        </tr>
                        <tr>
                       
                    </table>
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            'nim',
                            'nama_user',
                            
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>

</div>

<?php
 
$script = <<< JS
    $(function () {
        $('#modalButton').click(function () {
            $('#modal-data').modal('show')
                .find('#content-modal-data')
                .load($(this).attr('value'));
        });
        
    });
    
    
    
JS;
$this->registerJs($script)
?>