final_project_DSC/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\RegistrationForm;
//use app\models\User;
//use hscstudio\mimin\models\AuthAssignment;
use app\models\TUser;
use app\modules\systemxadmin\models\User;
use app\modules\systemxadmin\models\AuthAssignment;
use app\modules\systemxadmin\models\AuthItem;
use app\modules\systemxadmin\models\UserSearch;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        
        if (!Yii::$app->user->isGuest) {
            //return $this->goHome();
            return $this->redirect(['site/index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
            //return $this->redirect(['site/index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);



    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /*
        Fungsi Register : Untuk menambahkan user baru
    */
    public function actionRegister()
    {
        
        $model = new User();
        $modelRole = new AuthAssignment();

        if ($model->load(Yii::$app->request->post())) {
            $password = $model->password_hash;
            //print_r($password);die;
            $model->setPassword($password);
            $model->status = 10;
            if ($model->save()) {
                $user = TUser::find()->where(['username' => $model->username])->andWhere(['email'=>$model->email])->one();
                $modelRole->item_name = "PESERTA";
                $modelRole->user_id = $user->id;

                if($modelRole->save()){
                    $email = \Yii::$app->mailer->compose()
                    ->setFrom(['henny.panjaitan3004@gmail.com'=>'Del Data Science Club'])
                    ->setTo($user->email)
                    ->setSubject('Informasi Pemberitahuan Verifikasi Jadi Anggota')
                    ->setHtmlBody('
                        <b>Terima Kasih Telah Melakukan Registrasi Pada Del Data Science Club</b>
                        <br><br>
                        <b>Akun anda telah diverifikasi, Silahkan LOGIN menggunakan username dan password yang anda daftarkan</b>')
                    ->send();

                    if($email){
                        Yii::$app->session->setFlash('success', "Registrasi User Berhasil");
                    }
                    
                }else{
                    $user->delete();
                    Yii::$app->session->setFlash('danger', 'Mohon Maaf, Registrasi User Gagal');
                }

                
            } else {
                Yii::$app->session->setFlash('danger', 'Mohon Maaf, Registrasi User Gagal');
            }

            return $this->redirect(['login']);
        } else {
            return $this->render('register_user', [
                'model' => $model,
            ]);
        }
        
    }

    public function actionViewProfile($id)
    {
        $model = User::findOne($id);
        
        return $this->render('view_profile', [
            'model' => $model,
            'id' => $id,
        ]);
    }


    public function actionUpdateuser($id)
    {
        $model = User::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
             
            $foto_profil = UploadedFile::getInstance($model, 'foto_profil');
            if (!is_null($foto_profil)) {
                $tmp = explode('.', $foto_profil->name);
                $ext_foto = end($tmp);
                //$ext_foto = end((explode(".", $image_foto->name)));
                  // generate a unique file name to prevent duplicate filenames
                $model->foto = Yii::$app->security->generateRandomString().".{$ext_foto}";
                
                // the path to save file, you can set an uploadPath
                // in Yii::$app->params (as used in example below)
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/foto_profil/';
                $path_foto = Yii::$app->params['uploadPath'] . $model->foto;
                
                $foto_profil->saveAs($path_foto);  
                    
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'User berhasil diupdate');
            } else {
                Yii::$app->session->setFlash('error', 'User gagal diupdate');
            }
            return $this->redirect(['view-profile','id'=>$id]);
        } else {
            
            return $this->renderAjax('_form_profil', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdatepassword($id)
    {
        $model = User::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if (!empty($model->new_password)) {
                $model->setPassword($model->new_password);
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Password berhasil diupdate');
            } else {
                Yii::$app->session->setFlash('error', 'Password gagal diupdate');
            }
            return $this->redirect(['view-profile','id'=>$id]);
        } else {
            
            return $this->renderAjax('_form_update_password', [
                'model' => $model,
            ]);
        }
    }

}

final_project_DSC/views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\SwitchInput;

/* @var $this yii\web\View */
/* @var $model app\modules\administrator\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

	<?php $form = ActiveForm::begin(); ?>
	<?= $form->field($model, 'nim')->textInput(['maxlength' => true]) ?>

	<?= $form->field($model, 'nama_user')->textInput(['maxlength' => true]) ?>

	<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

	<?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

	<?= $form->field($model, 'password_hash')->passwordInput(['id'=>'new_password']) ?>
		
	<?= Html::checkbox('reveal-password', false, ['id' => 'reveal-password']) ?> <?= Html::label('Show password', 'reveal-password') ?>
	<div class="text-danger">
        * Silahkan Isi Data Pengguna Dengan Baik dan Tidak Boleh Kosong.
    </div>
    <br>
	<div class="form-group">
		<center><?= Html::submitButton($model->isNewRecord ? 'DAFTARKAN' : 'DAFTARKAN', ['class' => $model->isNewRecord ? 'btn btn-success btn-lg' : 'btn btn-primary']) ?></center>
	</div>

	<?php ActiveForm::end(); ?>

</div>

<?php
 
$script = <<< JS
    $(function () {
        $('#reveal-password').change(function () {
            $('#new_password').attr('type',this.checked?'text':'password');
            //$('#repeat_password').attr('type',this.checked?'text':'password');
            //$('#old_password').attr('type',this.checked?'text':'password');
        });
        
    });
    
    
    
JS;
$this->registerJs($script)
?>

final_project_DSC/views/site/_form_profil.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\SwitchInput;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\modules\administrator\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Update Data User';
?>


<div class="user-form">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-6">
	    	<div class="box box-solid box-success">
	     		<div class="box-body">
	     			
	     			<?php $form = ActiveForm::begin(); ?>

					<?= $form->field($model, 'username')->textInput(['maxlength' => true,'disabled' => true]) ?>

					<?= $form->field($model, 'nim')->textInput(['maxlength' => true]) ?>

					<?= $form->field($model, 'nama_user')->textInput(['maxlength' => true]) ?>

					<?= $form->field($model, 'telp')->textInput(['maxlength' => true]) ?>

					<?= $form->field($model, 'status')->hiddenInput(['value'=> 10])->label(false);?>

					<?= $form->field($model, 'foto_profil')->widget(FileInput::classname(), 
                        [
                            'options' => ['accept' => 'image/*'],
                            'pluginOptions'=>[
                                'allowedFileExtensions'=>['jpg','jpeg','png'],
                                'dropZoneEnabled'=> false,
                                'browseLabel' =>  'Upload Foto Profil'
                            ],
                        ]) 
                    ?>    
					
					<div class="form-group">
						<center>
							<?= Html::submitButton($model->isNewRecord ? 'Update Data User' : 'Update Data User', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-success']) ?>
						</center>
					</div>

					<?php ActiveForm::end(); ?>
	     		</div>
	     	</div>
	     </div>
     </div>
</div>

final_project_DSC/views/site/_form_update_password.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\SwitchInput;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\modules\administrator\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

	<?php $form = ActiveForm::begin(); ?>

	<?php if (!$model->isNewRecord) { ?>
		<div class="ui divider"></div>
		<?= $form->field($model, 'old_password')->passwordInput(['id'=>'old_password']) ?>
		<?= $form->field($model, 'new_password')->passwordInput(['id'=>'new_password']) ?>
		<?= $form->field($model, 'repeat_password')->passwordInput(['id'=>'repeat_password']) ?>
		

		<?= Html::checkbox('reveal-password', false, ['id' => 'reveal-password']) ?> <?= Html::label('Show password', 'reveal-password') ?>

	<?php } ?>
	<div class="form-group">
		<center>
			<?= Html::submitButton($model->isNewRecord ? 'SIMPAN PASSWORD BARU' : 'SIMPAN PASSWORD BARU', ['class' => $model->isNewRecord ? 'btn btn-primary' : 'btn btn-primary']) ?>
		</center>
	</div>

	<?php ActiveForm::end(); ?>

</div>

<?php
 
$script = <<< JS
    $(function () {
        $('#reveal-password').change(function () {
            $('#new_password').attr('type',this.checked?'text':'password');
            $('#repeat_password').attr('type',this.checked?'text':'password');
            $('#old_password').attr('type',this.checked?'text':'password');
        });
        
    });
    
    
    
JS;
$this->registerJs($script)
?>

final_project_DSC/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

final_project_DSC/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

final_project_DSC/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

final_project_DSC/views/site/index.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use kartik\select2\Select2;
/* @var $this yii\web\View */
/* @var $model app\models\Tantangan */

$this->title = 'Home';


?>
<div class="tantangan-view">
    <div class="row">
    	<div class="col-md-12 col-sm-12 col-xs-12">
          <div class="info-box">
            <!-- <span class="info-box-icon bg-aqua"></i></span> -->

            <div class="info-box-content">
   			<h1 class="text-purple">
   			 <?php
           	 $urlImage = Yii::getAlias('@web').'/images/del.jpeg';
       		 ?>    
        	       <img src="<?= $urlImage;?>" alt="Logo Image" style="height: 10%;width: 10%;"/>
   					&nbsp &nbsp &nbsp &nbsp &nbsp<b> WELCOME TO DEL DATA SCIENCE CLUB</b> &nbsp &nbsp &nbsp &nbsp
              <?php
           	 $urlImage = Yii::getAlias('@web').'/images/logo_dsc.png';
       		 ?>    
        	<img src="<?= $urlImage;?>" alt="Logo Image" style="height: 12%;width: 12%;"/>
       		 </h1>

              <span class="info-box-number"></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12">
        	
            <ul class="timeline">
                <!-- timeline time label -->
                <li class="time-label">
                    <span class="bg-green">
                      <h4>VISI MISI DEL DATA SCIENCE CLUB</h4>
                    </span>
                    
                </li>
               
                <li>
                    <!-- timeline icon -->
                    <i class="fa fa-area-chart bg-red"></i>
                    <div class="timeline-item">
                        <span class="time">
                        </span>

                        <h3 class="timeline-header">
                            <b class="text-primary">VISI </b>
                        </h3>

                        <div class="timeline-body">
                         
			            Menjadikan Klub Ilmu Data Del sebagai wadah pengembangan kreativitas mahasiswa dan masyarakat dalam bidang ilmu data<br>
                    </div>
                </li>
                
                <li>
                
                    <i class="fa fa-area-chart bg-yellow"></i>
                    <div class="timeline-item">
                       	<h3 class="timeline-header">
          					 <b class="text-primary">MISI </b>
                        </h3>

                        <div class="timeline-body">
                         

                       1. Sebagai wadah dalam meningkatkan serta mengembangkan minat dan bakat mahasiswa khususnya anggota klub dalam bidang ilmu data.<br>
			            2. Menyelenggarakan berbagai perlombaan di bidang ilmu data yang bisa diikuti khalayak umum.<br>
			            3. Menjalin kerjasama antarkomunikasi ilmu data dari berbagai universitas maupun komunitas lain.<br>
			            4. Menyebarluaskan dan mengimplementasikan peran dan fungsi ilmu data dalam kehidupan bermasyarakat.
                        </div>

                    </div>
                </li>

            </ul>
        </div>

         <div class="col-lg-6 col-md-12 col-sm-12">
        	
            <ul class="timeline">
                <!-- timeline time label -->
                <li class="time-label">
                    <span class="bg-purple">
                      <h4>STRUKTUR ORGANISASI</h4>
                    </span>
                    
                </li>
               
                <li>
                    <!-- timeline icon -->
                    <i class="fa fa-user bg-teal"></i>
                    <div class="timeline-item">
                        <span class="time">
                        </span>

                        <h3 class="timeline-header">
                            <b class="text-yellow">PEMBINA </b>
                        </h3>

                        <div class="timeline-body">
                         <b class="text-primary">Samuel Indra Gunawan Situmeang, S.Ti.,M.Sc.</b>
			            <br>
                    </div>
                </li>
                
                <li>
                
                    <i class="fa fa-users bg-maroon"></i>
                    <div class="timeline-item">
                       	<h3 class="timeline-header">
          					 <b class="text-yellow">PENGURUS </b>
                        </h3>


                        <div class="timeline-body">
                   		
                    	<b class="text-primary"> 
                        KETUA     : Irvandy Sihombing<br>
                   		WAKIL     : Unedo Manalu<br>
                   		BENDAHARA : Christopher<br>
                   		SEKRETARIS: Agnes <br>
                    </b>

                   		

                        </div>

                    </div>
                </li>

            </ul>
        </div>
        
        
    </div>
        </div>
    </div>



</div>

final_project_DSC/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Sign In';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box" >
    <center><h4><a href="#"><b class="text-success">DEL DATA SCIENCE CLUB</b></a></h4></center>
    <div class="login-logo">
        <?php
            $urlImage = Yii::getAlias('@web').'/images/logo.png';
        ?>    
        <img src="<?= $urlImage;?>" alt="Logo Image" style="height: 35%;width: 35%;"/>
        
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Silahkan LOGIN Ke Dalam Aplikasi</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <br>
            <div class="col-xs-12">
                <?= Html::submitButton('LOGIN', ['class' => 'btn btn-success btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>
        <hr>
        <p class="text-danger">Belum Memiliki Akun?, Silahkan Klik "DAFTAR AKUN (REGISTER)"</p>
        <div class="social-auth-links text-center">
            

            <?= Html::a('<span class="fa fa-vcard"></span>DAFTAR AKUN (REGISTER)', ['site/register'], ['class' => 'btn btn-block btn-social btn-facebook btn-flat']) ?>
        </div>

    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

final_project_DSC/views/site/register.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Tambah User Baru';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'fullname')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'role')->dropDownList([ 'Admin' => 'Admin', 'Mahasiswa' => 'Mahasiswa'], ['prompt' => 'Pilih Role']) ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>


                <div class="form-group">
                    <?= Html::submitButton('Register', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
   
</div>

final_project_DSC/views/site/register_user.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\administrator\models\User */

$this->title = 'DAFTAR PENGGUNA';
/*$this->params['breadcrumbs'][] = $this->title;*/
?>
<div class="user-create">
	<div class="row">
		<br><br>
		<div class="col-lg-3 col-md-3 col-sm-3">
			
		</div>
		<div class="col-lg-6 col-md-6 col-sm-6">
			<div class="box box-success">
                <div class="box-header with-border">
                    <center>
                      <center><h2>FORM DAFTAR PENGGUNA BARU</h2></center>
                    </center>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                	<?= $this->render('_form', [
				        'model' => $model,
				    ]) ?>
                </div>
            </div>
		</div>
	</div>
    

</div>

final_project_DSC/views/site/view_profile.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KategoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Data Profile';

?>

<?php
        
    Modal::begin([
        'header' => '<center><h4>FORM PROFILE</h4></center>',
        'id' => 'modal-data',
        'size' => 'modal-md',
        'options' => [
              'tabindex' => false, 
          ],
    ]);

    echo '<div id="content-modal-data"></div>';
    Modal::end();
?>

<?php
        
    Modal::begin([
        'header' => '<center><h4>FORM UPDATE PASSWORD</h4></center>',
        'id' => 'modal-data2',
        'size' => 'modal-md',
        'options' => [
              'tabindex' => false, 
          ],
    ]);

    echo '<div id="content-modal-data2"></div>';
    Modal::end();
?>

<div class="kategori-index">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-6">
            <div class="box box-success">
                <div class="box-header with-border">
                    <center>
                      <h3 class="text-success">DATA PROFILE USER</h3>
                    </center>
                    <p align="right">
                        <?= Html::button('<span class="fa fa-user-circle-o"></span> UPDATE PROFILE', ['id' => 'modalButton', 'value' => \yii\helpers\Url::to(['site/updateuser','id'=>$id]), 'class' => 'btn btn-success']) ?>

                        <?= Html::button('<span class="glyphicon glyphicon-pencil"></span> UPDATE PASSWORD', ['id' => 'modalButton2', 'value' => \yii\helpers\Url::to(['updatepassword','id'=>$id]), 'class' => 'btn btn-primary']) ?>
                    </p>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?= DetailView::widget([
                          'model' => $model,
                          'attributes' => [
                              'nim',
                              'nama_user',
                              'username',
                              'email',
                              'telp',
                              
                              [
                                'attribute' => 'status',
                                'format' => 'raw',
                                'value' => function ($data) {
                                  if ($data->status == 10)
                                    return "<span class='label label-success'>" . 'USER AKTIF' . "</span>";
                                  else
                                    return "<span class='label label-danger'>" . 'USER NON AKTIF' . "</span>";
                                }
                              ],

                              [
                                'attribute' => 'Role',
                                'format' => 'raw',
                                'value' => function ($data) {
                                  $roles = [];
                                  foreach ($data->roles as $role) {
                                    $roles[] = $role->item_name;
                                  }
                                  return "<span class='label label-danger'>" . (implode(', ', $roles)). "</span>";
                                }
                              ],

                              [
                                'attribute'=>'foto',
                                'format' => 'raw',
                                'value' => function ($data) {
                                  if (is_null($data->foto)){
                                    return "Foto User Belum Ada";
                                  }
                                    
                                  else{
                                    $urlImage = Yii::getAlias('@web').'/foto_profil/'.$data->foto;
                                    return '<img src="'.$urlImage.'" style="height: 100px;width: 100px;"/>';
                                  }
                                    
                                }

                                

                                
                             ],
                              
                                 
                          ],
                      ]) ?>

                </div>
            </div>
        </div>
    </div>

</div>

<?php
 
$script = <<< JS
    $(function () {
        $('#modalButton').click(function () {
            $('#modal-data').modal('show')
                .find('#content-modal-data')
                .load($(this).attr('value'));
        });

        $('#modalButton2').click(function () {
            $('#modal-data2').modal('show')
                .find('#content-modal-data2')
                .load($(this).attr('value'));
        });
        
    });
    
    
    
JS;
$this->registerJs($script)
?>