final_project_DSC/models/Tantangan.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
/**
 * This is the model class for table "tantangan".
 *
 * @property int $id_tantangan
 * @property string $judul_tantangan
 * @property string|null $deskripsi_tantangan
 * @property string $waktu_buka
 * @property string $waktu_tutup
 * @property string $file_tantangan
 * @property string|null $created_at
 * @property int|null $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 *
 * @property SubmitTantangan[] $submitTantangans
 * @property TUser[] $users
 */
class Tantangan extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */

    public $file;

    public static function tableName()
    {
        return 'tantangan';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['judul_tantangan', 'waktu_buka', 'waktu_tutup', 'file_tantangan','id_setting'], 'required'],
            [['waktu_buka', 'waktu_tutup', 'created_at', 'updated_at'], 'safe'],
            [['created_by', 'updated_by','id_setting'], 'integer'],
            [['judul_tantangan', 'file_tantangan'], 'string', 'max' => 255],
            [['deskripsi_tantangan'], 'string'],

            [['file'], 'safe'],
            [['file'], 'file', 'extensions'=>'jpg, jpeg, png, tif, pdf, docx, doc, zip, rar'],
            [['file'], 'file', 'maxSize' => 1024 * 1024 * 1024 * 1024],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_tantangan' => 'Id Tantangan',
            'judul_tantangan' => 'Judul Tantangan',
            'deskripsi_tantangan' => 'Deskripsi Tantangan',
            'waktu_buka' => 'Waktu Buka',
            'waktu_tutup' => 'Waktu Tutup',
            'file_tantangan' => 'File Tantangan',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'id_setting' => 'ID Setting',
        ];
    }

    public function behaviors()
    {
       return [
           'timestamp' => [
               'class' => TimestampBehavior::className(),
               'attributes' => [
                   ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                   ActiveRecord::EVENT_BEFORE_UPDATE => 'updated_at',
               ],
               'value' => new Expression('NOW()'),
           ],

       ];
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }
        if(ActiveRecord::EVENT_BEFORE_INSERT){
            $this->created_by = Yii::$app->user->identity->id;
            $this->updated_by = Yii::$app->user->identity->id;
        }else if(ActiveRecord::EVENT_BEFORE_UPDATE){
            $this->updated_by = Yii::$app->user->identity->id;
        }

        return true;
    }

    /**
     * Gets query for [[SubmitTantangans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSubmitTantangans()
    {
        return $this->hasMany(SubmitTantangan::className(), ['id_tantangan' => 'id_tantangan']);
    }

    /**
     * Gets query for [[Users]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(TUser::className(), ['id' => 'id_user'])->viaTable('submit_tantangan', ['id_tantangan' => 'id_tantangan']);
    }
}

final_project_DSC/controllers/TantanganController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tantangan;
use app\models\TantanganSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Setting;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;
use app\modules\systemxadmin\models\User;
use app\modules\systemxadmin\models\AuthAssignment;
use app\modules\systemxadmin\models\AuthItem;
use app\modules\systemxadmin\models\UserSearch;
use app\models\SubmitTantangan;
/**
 * TantanganController implements the CRUD actions for Tantangan model.
 */
class TantanganController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tantangan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $setting = Setting::find()->where(['active'=>10])->orderBy(['id_setting' => 'DESC'])->one();

        $arrayTahun = ArrayHelper::map(Setting::find()->orderBy(['id_setting' => 'DESC'])->all(),'id_setting','tahun_aktif');

        $tantangan = Tantangan::find()->where(['id_setting' => $setting->id_setting])->orderBy(['id_tantangan'=>SORT_DESC])->all();

        $pembina = User::find()->join('JOIN','auth_assignment','auth_assignment.user_id = t_user.id')->where(['auth_assignment.item_name'=>'PEMBINA'])->all();
        $countAnggota =  User::find()->join('JOIN','auth_assignment','auth_assignment.user_id = t_user.id')->where(['auth_assignment.item_name'=>'ANGGOTA'])->count();

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchAnggota(Yii::$app->request->queryParams);

        $user = Yii::$app->user->identity;
        $role = AuthAssignment::find()->where(['user_id'=>$user->id])->one();

        return $this->render('index', [
            'setting' => $setting,
            'tantangan' => $tantangan,
            'arrayTahun' => $arrayTahun,
            'pembina' => $pembina,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'countAnggota' => $countAnggota,
            'role' => $role,
        ]);
    }

    /**
     * Displays a single Tantangan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $model_user = User::find()->where(['id'=>$model->updated_by])->one();

        $user = Yii::$app->user->identity;
        $role = AuthAssignment::find()->where(['user_id'=>$user->id])->one();

        $submit_tantangan = SubmitTantangan::find()->where(['id_tantangan'=>$id])->andWhere(['id_user'=>$user->id])->one();
        if (is_null($submit_tantangan)) {
            $model_submit = new SubmitTantangan();
        }else{
            $model_submit = $submit_tantangan;
        }

        return $this->render('view', [
            'model' => $model,
            'model_user' => $model_user,
            'role' => $role,
            'model_submit' => $model_submit,
            'user' => $user,
            'submit_tantangan' => $submit_tantangan,
        ]);
    }

    /**
     * Creates a new Tantangan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tantangan();

        $setting = Setting::find()->where(['active'=>10])->orderBy(['id_setting' => 'DESC'])->one();
        
        if ($model->load(Yii::$app->request->post())) {
             
            $file = UploadedFile::getInstance($model, 'file');
            if (!is_null($file)) {
                $tmp = explode('.', $file->name);
                $ext_foto = end($tmp);
                //$ext_foto = end((explode(".", $image_foto->name)));
                  // generate a unique file name to prevent duplicate filenames
                $model->file_tantangan = Yii::$app->security->generateRandomString().".{$ext_foto}";
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/upload/tantangan/';
                $path_file = Yii::$app->params['uploadPath'] . $model->file_tantangan;
                
                $file->saveAs($path_file);  
            }
            $model->id_setting = $setting->id_setting;
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Tantangan Berhasil Diupload');
            } else {
                Yii::$app->session->setFlash('danger', 'Tantangan Gagal Diupload');
            }

            return $this->redirect(['index']);
        } else {
            
            return $this->render('create', [
                'model' => $model,
                
            ]);
        }
    }

    /**
     * Updates an existing Tantangan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $setting = Setting::find()->where(['active'=>10])->orderBy(['id_setting' => 'DESC'])->one();
        
        if ($model->load(Yii::$app->request->post())) {
             
            $file = UploadedFile::getInstance($model, 'file');
            if (!is_null($file)) {
                $tmp = explode('.', $file->name);
                $ext_foto = end($tmp);
                //$ext_foto = end((explode(".", $image_foto->name)));
                  // generate a unique file name to prevent duplicate filenames
                $model->file_tantangan = Yii::$app->security->generateRandomString().".{$ext_foto}";
                Yii::$app->params['uploadPath'] = Yii::$app->basePath . '/web/upload/tantangan/';
                $path_file = Yii::$app->params['uploadPath'] . $model->file_tantangan;
                
                $file->saveAs($path_file);  
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Tantangan Berhasil Diupdate');
            } else {
                Yii::$app->session->setFlash('danger', 'Tantangan Gagal Diupdate');
            }

            return $this->redirect(['index']);
        } else {
            
            return $this->render('update', [
                'model' => $model,
                
            ]);
        }
    }

    /**
     * Deletes an existing Tantangan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tantangan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Tantangan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tantangan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /*
        Fungsi Untuk Melihat Status Submit Tantangan
    */

    public function actionStatusSubmit($id_tantangan)
    {

        $model = User::find()->join('JOIN','auth_assignment','auth_assignment.user_id = t_user.id')->where(['auth_assignment.item_name'=>'ANGGOTA']);

        $tantangan = $this->findModel($id_tantangan);
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchListUser($model,Yii::$app->request->queryParams);

        return $this->render('status_submit', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'tantangan' => $tantangan,
        ]);
    }

    public function actionRekapitulasiNilai($id_tantangan)
    {

        $model = User::find()->join('JOIN','auth_assignment','auth_assignment.user_id = t_user.id')->where(['auth_assignment.item_name'=>'ANGGOTA']);
        $tantangan = $this->findModel($id_tantangan);
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->searchListUser($model,Yii::$app->request->queryParams);

        return $this->render('rekapitulasi_nilai', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'tantangan' => $tantangan,
        ]);
    }

    public function actionUpdateNilaiTantangan($id_tantangan,$id_user)
    {

        $model = SubmitTantangan::find()->where(['id_tantangan'=>$id_tantangan])->andWhere(['id_user'=>$id_user])->one();

        if ($model->load(Yii::$app->request->post())) {
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Nilai Berhasil Disimpan');
            } else {
                Yii::$app->session->setFlash('danger', 'Nilai Gagal Disimpan');
            }

            return $this->redirect(['status-submit','id_tantangan'=>$id_tantangan]);
        } else {
            
            return $this->renderAjax('update_nilai_tantangan', [
                'model' => $model,
                
            ]);
        }
    }


}

final_project_DSC/views/tantangan/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use skeeks\yii2\ckeditor\CKEditorWidget;
use skeeks\yii2\ckeditor\CKEditorPresets;
use kartik\widgets\DateTimePicker;
/* @var $this yii\web\View */
/* @var $model app\models\Tantangan */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tantangan-form">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="box box-success">
                <div class="box-header with-border">
                    <center><h3>FORM UPLOAD TANTANGAN</span></h3></center>
                    <p align="right">
                        <?= Html::a('<span class="glyphicon glyphicon-step-backward"></span>Kembali', ['tantangan/index'], ['class' => 'btn btn-default']) ?>
                    </p>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php $form = ActiveForm::begin(); ?>

                    <?= $form->field($model, 'judul_tantangan')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'deskripsi_tantangan')->widget(CKEditorWidget::className(), [
                        'options' => ['rows' => 3],
                        'preset' => CKEditorPresets::FULL
                    ]) ?>

                    <?= $form->field($model, 'file')->widget(FileInput::classname(), 
                        [
                            'pluginOptions'=>[
                                'allowedFileExtensions'=>['jpg','jpeg','png','pdf','docx','doc','zip','rar'],
                                'dropZoneEnabled'=> false,
                                'browseLabel' =>  'Upload Deskripsi File Tantangan'
                            ],
                        ]) 
                    ?>
                    <table class="table">
                        <tr>
                            <td>
                                <?= $form->field($model, 'waktu_buka')->widget(DateTimePicker::classname(), [
                                    'options' => ['placeholder' => 'Waktu Buka'],
                                    'pluginOptions' => [
                                        'autoclose' => true
                                    ]
                                ]); ?>
                            </td>
                            <td>
                                <?= $form->field($model, 'waktu_tutup')->widget(DateTimePicker::classname(), [
                                    'options' => ['placeholder' => 'Waktu Tutup'],
                                    'pluginOptions' => [
                                        'autoclose' => true
                                    ]
                                ]); ?>
                            </td>
                        </tr>
                    </table>

                    <div class="form-group">
                        <center><?= Html::submitButton('SIMPAN TANTANGAN', ['class' => 'btn btn-success']) ?></center>
                    </div>

                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>

final_project_DSC/views/tantangan/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TantanganSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tantangan-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_tantangan') ?>

    <?= $form->field($model, 'judul_tantangan') ?>

    <?= $form->field($model, 'deskripsi_tantangan') ?>

    <?= $form->field($model, 'waktu_buka') ?>

    <?= $form->field($model, 'waktu_tutup') ?>

    <?php // echo $form->field($model, 'file_tantangan') ?>

    <?php // echo $form->field($model, 'id_setting') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

final_project_DSC/views/tantangan/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tantangan */

$this->title = 'Upload Tantangan';

?>
<div class="tantangan-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

final_project_DSC/views/tantangan/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\db\Expression;
/* @var $this yii\web\View */
/* @var $searchModel app\models\KategoriSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Tantangan';

//$this->params['breadcrumbs'][] = $this->title;
?>

<?php
        
    Modal::begin([
        'header' => '<center><h4>DATA</h4></center>',
        'id' => 'modal-data',
        'size' => 'modal-md',
        'options' => [
              'tabindex' => false, 
          ],
    ]);

    echo '<div id="content-modal-data"></div>';
    Modal::end();
?>

<?php
    $bulan = array(
                '01' => 'Januari',
                '02' => 'Februari',
                '03' => 'Maret',
                '04' => 'April',
                '05' => 'Mei',
                '06' => 'Juni',
                '07' => 'Juli',
                '08' => 'Agustus',
                '09' => 'September',
                '10' => 'Oktober',
                '11' => 'November',
                '12' => 'Desember',
            );
?>

<div class="kategori-index">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <div class="box box-success">
                <div class="box-header with-border">
                    <table class="table">
                        <tr>
                            <td colspan="2" align="center"><h4>TANTANGAN <b class="text-success">DEL DATA SCIENCE CLUB</b></h4></td>
                            
                            <td align="right">
                                <?php
                                    if($role->item_name == 'PEMBINA' || $role->item_name == 'ADMINISTRATOR' || $role->item_name == 'PENGURUS'){
                                        echo Html::a('<span class="glyphicon glyphicon-cloud-upload"></span> UPLOAD TANTANGAN', ['tantangan/create'], ['class' => 'btn btn-success']);
                                    } 
                                     
                                ?>
                            </td>
                        </tr>
                    </table>
                    <p align="right">
                        Waktu Sekarang :
                        <?php
                            date_default_timezone_set('Asia/Jakarta');
                            $time = date('d-m-Y H:i');
                            //echo "<b>".$time.'</b>';

                            echo date('d',strtotime($time)).' '.($bulan[date('m',strtotime($time))]).' '.date('Y',strtotime($time)).' | <b class="text-success">'.date('h',strtotime($time)).':'.date('i',strtotime($time)).'</b>';
                        ?>
                    </p>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <?php
                        if(is_null($tantangan)){
                            echo "Tantangan Saat Ini Belum Ada";
                        }else{
                            
                            $i = 1;
                            foreach ($tantangan as $key => $value) {
                                                           
                    ?>
                            <ul class="products-list product-list-in-box">
                                <li class="item">
                                  <div class="product-img">
                                    <i class="fa fa-file-code-o fa-3x"></i>
                                  </div>
                                  <div class="product-info">
                                    <table class="table">
                                        <tr>
                                            <td>
                                                <?php
                                                    $now = strtotime($time); 
                                                    $open = strtotime($value['waktu_buka']);
                                                    if ($now >= $open) {
                                                        echo Html::a('<h4>'.$value['judul_tantangan'].'</h4>', ['tantangan/view','id'=>$value['id_tantangan']], ['class' => '']);
                                                    }
                                                    else{
                                                        echo '<h4>'.$value['judul_tantangan'].'</h4>';
                                                    }
                                                     
                                                ?>
                                            </td>
                                            <td align="right">
                                                <?php
                                                    if($role->item_name == 'PEMBINA' || $role->item_name == 'ADMINISTRATOR' || $role->item_name == 'PENGURUS'){
                                                        echo Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['update', 'id' => $value['id_tantangan']], ['class' => 'btn btn-warning btn-sm','title' => 'EDIT TANTANGAN',
                                                        'data-toggle' => 'tooltip']);
                                                        echo "&nbsp";
                                                        echo Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'id' => $value['id_tantangan']], ['class' => 'btn btn-danger btn-sm','title' => 'HAPUS TANTANGAN',
                                                                'data-toggle' => 'tooltip','data' => [
                                                                'confirm' => 'Apakah anda yakin menghapus data ini?',
                                                                'method' => 'post',
                                                                
                                                            ],
                                                        ]);
                                                    } 
                                                     
                                                ?>
                                            </td>
                                        </tr>
                                    </table>
                                    

                                    <a href="javascript:void(0)" class="product-title">
                                      <span class="label label-info pull-right"><?= "Tantangan ".$i;?></span></a>
                                    <span class="product-description">
                                        <table class="table">
                                            <tr>
                                                <td>Open : 
                                                    <?php
                                                        echo date('d',strtotime($value['waktu_buka'])).' '.($bulan[date('m',strtotime($value['waktu_buka']))]).' '.date('Y',strtotime($value['waktu_buka'])).' | <b class="text-success">'.date('h',strtotime($value['waktu_buka'])).':'.date('i',strtotime($value['waktu_buka'])).'</b>';
                                                    ?>
                                                </td>
                                                <td>Close :
                                                    <?php
                                                        echo date('d',strtotime($value['waktu_tutup'])).' '.($bulan[date('m',strtotime($value['waktu_tutup']))]).' '.date('Y',strtotime($value['waktu_tutup'])).' | <b class="text-success">'.date('h',strtotime($value['waktu_tutup'])).':'.date('i',strtotime($value['waktu_tutup'])).'</b>';
                                                    ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </span>
                                  </div>
                                </li>
                               
                            </ul>
                    <?php
                                $i++;
                            }        
                        }
                    ?>

                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-4">
            <div class="box box-solid box-success">
                <div class="box-header with-border">
                    <center>
                      KETERANGAN TANTANGAN
                    </center>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table">
                        <tr>
                            <th>Filter Tantangan</th>
                        </tr>
                        <tr>
                            <td>
                                <?php
                                    echo Select2::widget([
                                        'name' => 'id_tahun',
                                        'data' => $arrayTahun,
                                        'options' => [
                                            'placeholder' => 'Filter Data Berdasarkan Tahun ...',
                                            'id'=>'id_tahun'
                                        ],
                                        'pluginOptions' => [
                                            'allowClear' => true
                                        ],
                                    ]);
                                ?>
                            </td>
                        </tr>


                        <tr>
                            <th>Pembina</th>
                        </tr>
                    <?php
                        foreach ($pembina as $key => $value) {
                    ?>
                        <tr align="center">
                            <td><h3 class="label label-primary"><?= $value['nama_user'];?></h3></td>
                        </tr>
                    <?php        
                        }
                    ?>
                        
                    </table>
                    
                </div>
            </div>

            <div class="box box-solid box-danger">
                <div class="box-header with-border">
                    <center>
                      DAFTAR ANGGOTA
                    </center>
                    
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table">
                        <tr>
                            <th>Jumlah Anggota : <?= Html::a($countAnggota.' orang', ['pengurus/list-user','role'=>'ANGGOTA'], ['class' => 'text-danger','title' => 'LIHAT DAFTAR ANGGOTA KESELURUHAN','data-toggle' => 'tooltip',]) ?></th>
                        </tr>
                        <tr>
                       
                    </table>
                    <?= GridView::widget([
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'columns' => [
                            ['class' => 'yii\grid\SerialColumn'],

                            'nim',
                            'nama_user',
                            
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>

</div>

<?php
 
$script = <<< JS
    $(function () {
        $('#modalButton').click(function () {
            $('#modal-data').modal('show')
                .find('#content-modal-data')
                .load($(this).attr('value'));
        });
        
    });
    
    
    
JS;
$this->registerJs($script)
?>

final_project_DSC/views/tantangan/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Tantangan */

$this->title = 'Update Tantangan';

?>
<div class="tantangan-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

final_project_DSC/views/tantangan/update_nilai_tantangan.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SubmitTantangan */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="submit-tantangan-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nilai')->textInput(['placeholder' => 'INPUT NILAI'])->label(false) ?>

    <div class="form-group">
        <center><?= Html::submitButton('SIMPAN NILAI', ['class' => 'btn btn-success']) ?></center>
    </div>

    <?php ActiveForm::end(); ?>

</div>